Connect to the Swiss Open Data API to retrieve the Income Data for the Canton of Zurich. Afterwards load the Data into a Dataframe and save the originally retrieved data into csv, before the cleaning of the Data.

In [11]:
import requests    
import json         
import pandas as pd 
import os

package = 'o-steuerbares-einkommen-naturliche-pers-fr'

# Base url for the open data swiss API
base_url = 'https://opendata.swiss/api/3/action/package_show?id='

# Construct the url including package 
package_information_url = base_url + package

# HTTP request
package_information = requests.get(package_information_url)

# Use the json module to load CKAN's response into a dictionary
package_dict = json.loads(package_information.content)

# Check the contents of the response.
assert package_dict['success'] is True  
package_dict = package_dict['result']   
print(package_dict)

{'documentation': [], 'maintainer': 'Statistisches Amt des Kantons Zürich, Data Shop', 'issued': '2016-01-20T20:16:00+01:00', 'title_for_slug': 'o-steuerbares-einkommen-naturliche-pers-fr', 'qualified_relations': [], 'private': False, 'maintainer_email': 'datashop@statistik.zh.ch', 'num_tags': 5, 'contact_points': [{'email': 'datashop@statistik.zh.ch', 'name': 'Statistisches Amt des Kantons Zürich, Data Shop'}], 'keywords': {'fr': [], 'de': ['kantonzuerich', 'bezirke', 'steuerbareseinkommen', 'natuerlichepersonen', 'gemeinden'], 'en': [], 'it': []}, 'temporals': [{'start_date': '1990-12-31T00:00:00', 'end_date': '2022-12-31T23:59:59.999999'}], 'id': '38c79917-5439-4bfb-8065-816344241af3', 'metadata_created': '2021-01-14T17:38:00.017252', 'owner_org': 'e7da7270-663b-4f96-910c-e4bffbf836f0', 'conforms_to': [], 'metadata_modified': '2024-04-01T04:47:58.079080', 'author': None, 'author_email': None, 'relations': [{'url': 'https://www.zh.ch/de/politik-staat/gesetze-beschluesse/gesetzessammlung/zhlex-os/erlass-431_1-70-359.html', 'label': 'legal_basis'}, {'url': 'https://openzh.github.io/starter-code-openZH/', 'label': 'Vorbereiteter Code in R oder Python für jedes Dataset mit csv-Datei(en)'}], 'state': 'active', 'version': None, 'relationships_as_object': [], 'license_id': None, 'see_alsos': [{'dataset_identifier': '55@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '189@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '188@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '187@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '30@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '29@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '190@statistisches-amt-kanton-zuerich'}, {'dataset_identifier': '137@statistisches-amt-kanton-zuerich'}], 'type': 'dataset', 'resources': [{'byte_size': 758010, 'cache_last_updated': None, 'issued': '2016-01-21T16:30:35+01:00', 'uri': '', 'package_id': '38c79917-5439-4bfb-8065-816344241af3', 'temporal_resolution': '', 'datastore_contains_all_records_of_source_file': False, 'datastore_active': False, 'id': '79b03343-9588-48dd-b7ec-8fa6de39c65f', 'size': None, 'rights': 'NonCommercialAllowed-CommercialAllowed-ReferenceRequired', 'display_name': {'fr': '', 'de': 'Ø steuerbares Einkommen natürliche Pers. [Fr.]', 'en': '', 'it': ''}, 'title': {'fr': '', 'de': 'Ø steuerbares Einkommen natürliche Pers. [Fr.]', 'en': '', 'it': ''}, 'download_url': 'https://www.web.statistik.zh.ch/ogd/data/KANTON_ZUERICH_282.csv', 'state': 'active', 'media_type': 'text/csv', 'hash': '', 'description': {'fr': '', 'de': '', 'en': '', 'it': ''}, 'format': 'CSV', 'language': ['de'], 'mimetype_inner': None, 'url_type': None, 'name': {'fr': '', 'de': 'Ø steuerbares Einkommen natürliche Pers. [Fr.]', 'en': '', 'it': ''}, 'mimetype': 'text/csv', 'cache_url': None, 'license': 'NonCommercialAllowed-CommercialAllowed-ReferenceRequired', 'access_services': [], 'created': '2022-12-12T03:05:47.211751', 'url': 'https://www.web.statistik.zh.ch/ogd/data/KANTON_ZUERICH_282.csv', 'documentation': [], 'modified': '2023-05-16T14:02:27+01:00', 'last_modified': None, 'position': 0, 'revision_id': '930938f3-0bba-4557-a38f-27fbbc9e5a87', 'resource_type': None}], 'num_resources': 1, 'description': {'fr': '', 'de': 'Durchschnittliches steuerbares Einkommen ordentlich besteuerter natürlichen Personen (exkl. Quellensteuerpflichtige und ausserhalb des Kt. wohnhafte). Hinweis: Sehr hohe Beträge einiger weniger Steuerpflichtigen wirken sich entsprechend stark auf den Mittelwert aus. Bis 1998: Reineinkommen.', 'en': '', 'it': ''}, 'tags': [{'vocabulary_id': None, 'state': 'active', 'display_name': 'bezirke', 'id': '1545b490-60bb-4ea8-bbf7-ae3169ab0d5e', 'name': 'bezirke'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'gemeinden', 'id': 'bd203e69-5ef0-453a-ac6e-86790de68cdf', 'name': 'gemeinden'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'kantonzuerich', 'id': '52fecd10-5cac-4fbc-a6ac-71869630c5e1', 'name': 'kantonzuerich'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'natuerlichepersonen', 'id': 'f1db1af8-b231-4d6e-a404-293481d9b002', 'name': 'natuerlichepersonen'}, {'vocabulary_id': None, 'state': 'active', 'display_name': 'steuerbareseinkommen', 'id': 'fd57aa06-ba0f-4b4e-8dd5-d4e3130bfbd3', 'name': 'steuerbareseinkommen'}], 'title': {'fr': '', 'de': 'Ø steuerbares Einkommen natürliche Pers. [Fr.]', 'en': '', 'it': ''}, 'groups': [{'display_name': {'fr': 'Économie et finances', 'de': 'Wirtschaft und Finanzen', 'en': 'Economy and finance', 'it': 'Economia e finanze'}, 'description': {'fr': '', 'de': '', 'en': '', 'it': ''}, 'title': {'fr': 'Économie et finances', 'de': 'Wirtschaft und Finanzen', 'en': 'Economy and finance', 'it': 'Economia e finanze'}, 'image_display_url': '', 'id': '34f50c10-ddd0-4e37-b5c0-49456b39e31a', 'name': 'econ'}], 'creator_user_id': 'af084126-f711-4016-a585-70354e997796', 'display_name': {'fr': '', 'de': 'Ø steuerbares Einkommen natürliche Pers. [Fr.]', 'en': '', 'it': ''}, 'relationships_as_subject': [], 'name': 'o-steuerbares-einkommen-naturliche-pers-fr', 'publisher': {'url': 'https://opendata.swiss/organization/statistisches-amt-kanton-zuerich', 'name': 'Statistisches Amt des Kantons Zürich'}, 'isopen': False, 'language': ['de'], 'accrual_periodicity': 'http://publications.europa.eu/resource/authority/frequency/ANNUAL', 'license_title': None, 'modified': '2023-05-16T14:02:27+01:00', 'url': 'https://www.zh.ch/de/politik-staat/gemeinden/gemeindeportraet.html', 'extras': [{'value': '138@statistisches-amt-kanton-zuerich', 'key': 'guid'}, {'value': 'https://ckan.opendata.swiss/perma/138@statistisches-amt-kanton-zuerich', 'key': 'uri'}], 'organization': {'display_name': {'fr': '', 'de': 'Statistisches Amt Kanton Zürich', 'en': '', 'it': ''}, 'description': {'fr': '', 'en': '', 'de': 'Das Statistische Amt ist das Kompetenzzentrum für die öffentliche Statistik im Kanton Zürich. Wir versorgen Bevölkerung, Verwaltung, Politik, Gemeinden, Medien, Firmen und sonstige Organisationen mit qualitativ hochstehenden Daten, Informationen und Fakten zum Kanton Zürich. Inhaltlich arbeiten wir unabhängig und objektiv.', 'it': ''}, 'image_display_url': 'https://ckan.opendata.swiss/uploads/group/statistisches_amt_kt_zh.png', 'url': 'https://www.zh.ch/de/direktion-der-justiz-und-des-innern/statistisches-amt.html', 'package_count': 352, 'created': '2015-12-04T12:41:05.028083', 'name': 'statistisches-amt-kanton-zuerich', 'is_organization': True, 'state': 'active', 'image_url': 'https://ckan.opendata.swiss/uploads/group/statistisches_amt_kt_zh.png', 'revision_id': '21b82c42-1339-4177-951b-b429198c3c9e', 'groups': [{'capacity': 'public', 'name': 'kanton-zuerich'}], 'type': 'organization', 'title': {'fr': '', 'de': 'Statistisches Amt Kanton Zürich', 'en': '', 'it': ''}, 'political_level': 'canton', 'num_followers': 0, 'id': 'e7da7270-663b-4f96-910c-e4bffbf836f0', 'tags': [], 'approval_status': 'approved'}, 'revision_id': '256ed735-1db1-496b-826a-a39993406ef5', 'identifier': '138@statistisches-amt-kanton-zuerich'}

In [12]:
# Get the url for the data from the dictionary
data_url = package_dict['resources'][0]['url']
print('Data url:' + data_url)

# Print the data format
data_format = package_dict['resources'][0]['format']
print('Data format:' + data_format)

Data url:https://www.web.statistik.zh.ch/ogd/data/KANTON_ZUERICH_282.csv
Data format:CSV

In [13]:
csv = ['comma-separated-values', 'CSV', 'csv']
if any(s in data_format for s in csv):     
     Einkommensdaten_df = pd.read_csv(data_url)
else:
    print('Sorry, the data format is not supported')
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,THEMA_NAME,SET_NAME,SUBSET_NAME,INDIKATOR_ID,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_KURZ,EINHEIT_LANG,Unnamed: 11
0,1,Aeugst a.A.,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],1990,61057,Fr.,Franken,NaN
1,1,Aeugst a.A.,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],1991,65860,Fr.,Franken,NaN
2,1,Aeugst a.A.,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],1992,68042,Fr.,Franken,NaN
3,1,Aeugst a.A.,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],1993,72606,Fr.,Franken,NaN
4,1,Aeugst a.A.,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],1994,72495,Fr.,Franken,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6554,0,Zürich - ganzer Kanton,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,67937,Fr.,Franken,NaN
6555,0,Zürich - ganzer Kanton,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,68818,Fr.,Franken,NaN
6556,0,Zürich - ganzer Kanton,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,69393,Fr.,Franken,NaN
6557,0,Zürich - ganzer Kanton,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,69538,Fr.,Franken,NaN
6558,0,Zürich - ganzer Kanton,Öffentliche Finanzen,Gemeindesteuern,Steuergrundlagen,282,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,68710,Fr.,Franken,NaN

In [ ]:
#Save original data files to csv, if the folder is not aleady created, it will be created
directory = 'Original_CSV_files'
current_directory = os.getcwd()

csv_path = os.path.join(current_directory, directory, 'Einkommensdaten_KantonZurich_2009_2023.csv')

# Create the directory if it doesn't exist
if not os.path.exists(os.path.join(current_directory, directory)):
    os.makedirs(os.path.join(current_directory, directory))

Einkommensdaten_df.to_csv(csv_path, index=False)
print(Einkommensdaten_df)

Drop not needed Columns, Filter the Data to the years 2009-2023, Delete the summarized Datarows an as well unify the Region Names so the data can be analyzed with the other available datasets. Afterwards save a Cleaned csv file to the Cleaned CSV Files folder.

In [14]:
Einkommensdaten_df.drop(['THEMA_NAME','SET_NAME','SUBSET_NAME','INDIKATOR_ID','EINHEIT_KURZ','Unnamed: 11'], axis=1, inplace=True)
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_LANG
0,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1990,61057,Franken
1,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1991,65860,Franken
2,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1992,68042,Franken
3,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1993,72606,Franken
4,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1994,72495,Franken
...,...,...,...,...,...,...
6554,0,Zürich - ganzer Kanton,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,67937,Franken
6555,0,Zürich - ganzer Kanton,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,68818,Franken
6556,0,Zürich - ganzer Kanton,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,69393,Franken
6557,0,Zürich - ganzer Kanton,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,69538,Franken
6558,0,Zürich - ganzer Kanton,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,68710,Franken

In [15]:
# Loesche alle Indizes, die den Wert '0' in der Spalte 'BFS_NR' haben da diese zusammengefasste Informationen pro Bezirk/Region enthalten
indizes_zu_loeschen = Einkommensdaten_df[Einkommensdaten_df['BFS_NR'] == 0].index
Einkommensdaten_df.drop(indizes_zu_loeschen, inplace=True)
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_LANG
0,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1990,61057,Franken
1,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1991,65860,Franken
2,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1992,68042,Franken
3,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1993,72606,Franken
4,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],1994,72495,Franken
...,...,...,...,...,...,...
5762,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,72357,Franken
5763,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,74154,Franken
5764,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,74697,Franken
5765,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,75281,Franken
5766,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,73135,Franken

In [16]:
Jahresindizes_zu_loeschen = Einkommensdaten_df[Einkommensdaten_df['INDIKATOR_JAHR'] < 2009].index
Einkommensdaten_df.drop(Jahresindizes_zu_loeschen, inplace=True)
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_LANG
19,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2009,82027,Franken
20,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2010,87080,Franken
21,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2011,79841,Franken
22,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2012,81087,Franken
23,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2013,80720,Franken
...,...,...,...,...,...,...
5762,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,72357,Franken
5763,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,74154,Franken
5764,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,74697,Franken
5765,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,75281,Franken
5766,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,73135,Franken

In [17]:
#Einige Datensätze beinhalten im Gemeindenamen (bis *) um zu indizieren dass die Rechnung sich auf die angegbenen JAhre bezieht. Um Redundanzen zu vermeiden, werden diese entfernt
indizesBis_zu_loeschen = Einkommensdaten_df[Einkommensdaten_df['GEBIET_NAME'].str.contains("\(bis ", na=False)].index
Einkommensdaten_df.drop(indizesBis_zu_loeschen, inplace=True)
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_LANG
19,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2009,82027,Franken
20,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2010,87080,Franken
21,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2011,79841,Franken
22,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2012,81087,Franken
23,1,Aeugst a.A.,Ø steuerbares Einkommen natürliche Pers. [Fr.],2013,80720,Franken
...,...,...,...,...,...,...
5762,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,72357,Franken
5763,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,74154,Franken
5764,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,74697,Franken
5765,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,75281,Franken
5766,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,73135,Franken

In [18]:
# Vereinheitlichen der Gemeindenamen
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Aeugst a.A.', 'Aeugst', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Affoltern a.A.', 'Affoltern', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Hausen a.A.', 'Hausen', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Kappel a.A.', 'Kappel', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Wettswil a.A.', 'Wettswil', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Berg a.I.', 'Berg', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Buch a.I.', 'Buch', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Thalheim a.d.Th.', 'Thalheim', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Langnau a.A.', 'Langnau', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Oetwil a.S.', 'Oetwil', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Uetikon a.S.', 'Uetikon', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Ellikon a.d.Th.', 'Ellikon', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Oetwil a.d.L.', 'Oetwil an der Limmat', regex=False)
Einkommensdaten_df['GEBIET_NAME'] = Einkommensdaten_df['GEBIET_NAME'].str.replace('Aesch ZH', 'Aesch', regex=False)
Einkommensdaten_df

,BFS_NR,GEBIET_NAME,INDIKATOR_NAME,INDIKATOR_JAHR,INDIKATOR_VALUE,EINHEIT_LANG
19,1,Aeugst,Ø steuerbares Einkommen natürliche Pers. [Fr.],2009,82027,Franken
20,1,Aeugst,Ø steuerbares Einkommen natürliche Pers. [Fr.],2010,87080,Franken
21,1,Aeugst,Ø steuerbares Einkommen natürliche Pers. [Fr.],2011,79841,Franken
22,1,Aeugst,Ø steuerbares Einkommen natürliche Pers. [Fr.],2012,81087,Franken
23,1,Aeugst,Ø steuerbares Einkommen natürliche Pers. [Fr.],2013,80720,Franken
...,...,...,...,...,...,...
5762,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2018,72357,Franken
5763,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2019,74154,Franken
5764,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2020,74697,Franken
5765,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2021,75281,Franken
5766,298,Wiesendangen,Ø steuerbares Einkommen natürliche Pers. [Fr.],2022,73135,Franken

In [19]:
directory = 'Cleaned_CSV_files'
current_directory = os.getcwd()

csv_path = os.path.join(current_directory, directory, 'Einkommensdaten_KantonZurich_2009_2023_Cleaned.csv')

# Create the directory if it doesn't exist
if not os.path.exists(os.path.join(current_directory, directory)):
    os.makedirs(os.path.join(current_directory, directory))

Einkommensdaten_df.to_csv(csv_path, index=False)
print(Einkommensdaten_df)

The DataFrame has been saved to '/Users/natalievintonjak/Documents/Data Science Project/SteuerbaresEinkommen_KantonZurich_2009_2022.csv'.

Print the Information for the Dataframe so we can create the Table for the Database correspondingly.

In [ ]:
Einkommensdaten_df.info()

Connect to the database and create a new table called Einkommensdaten. If the table is already existing drop it.

In [ ]:
import mysql.connector
from mysql.connector import Error
import pandas as pd

# MySQL connection parameters
host = 'localhost'
user = 'admin'
password = 'Criminal1234'
database = 'CriminalDataDB'  
try:
    connection = mysql.connector.connect(host=host,
                                         user=user,
                                         password=password,
                                         database=database)

    if connection.is_connected():
        print("Connected to MySQL server")
        cursor = connection.cursor()

        # SQL command to drop the table if it already exists becuase before that line of code the data was already inserted multiple times
        drop_table_query = "DROP TABLE IF EXISTS Einkommensdaten;"
        cursor.execute(drop_table_query)
        print("Table 'Einkommensdaten' dropped if it existed alreadyy")

        create_table_query = """
        CREATE TABLE IF NOT EXISTS Einkommensdaten (
            BFS_NR INT,
            GEBIET_NAME VARCHAR(255),
            INDIKATOR_NAME VARCHAR(255),
            INDIKATOR_JAHR INT,
            INDIKATOR_VALUE FLOAT,
            EINHEIT_LANG VARCHAR(255)
        )
        """

        cursor.execute(create_table_query)
        print("Table 'Einkommensdaten' created successfully")

except Error as e:
    print("Error connecting to MySQL:", e)

finally:
    if connection.is_connected():
        # Close cursor and connection
        cursor.close()
        connection.close()
        print("MySQL connection closed")

Insert the Cleanaed data from the Cleaned Csv file which was created before.

In [ ]:
import mysql.connector 
from mysql.connector import Error
import pandas as pd

# MySQL connection parameters
connection_params = {
    'host': 'localhost',
    'user': 'admin',
    'password': 'Criminal1234',
    'database': 'CriminalDataDB',
    'allow_local_infile': True
}

directory = 'Cleaned_CSV_files'
current_directory = os.getcwd()
csv_file_path = os.path.join(current_directory, directory, 'Einkommensdaten_KantonZurich_2009_2023_Cleaned.csv')

try:
    with mysql.connector.connect(**connection_params) as connection:
        print("Connected to MySQL server")

        Bevoelkerungsdichte_df_to_sql = pd.read_csv(csv_file_path)

        cursor = connection.cursor()
        insert_query = """
        LOAD DATA LOCAL INFILE %s 
        INTO TABLE Einkommensdaten 
        FIELDS TERMINATED BY ',' 
        ENCLOSED BY '"' 
        LINES TERMINATED BY '\n' 
        IGNORE 1 LINES
        """

        cursor.execute(insert_query, (csv_file_path,))
        connection.commit()

        print("Data from CSV file successfully inserted into MySQL table 'Einkommensdaten'")

except Error as e:
    print("Error connecting to MySQL:", e)

finally:
    if connection.is_connected():
        # Close cursor and connection
        cursor.close()
        connection.close()
        print("MySQL connection closed")

Check if the Data upload to the table was successfully by creating a query to the sql table.

In [ ]:
import mysql.connector
from mysql.connector import Error

# MySQL connection parameters
connection_params = {
    'host': 'localhost',
    'user': 'admin',
    'password': 'Criminal1234',
    'database': 'CriminalDataDB'
}

try:
    connection = mysql.connector.connect(**connection_params)
    print("Connected to MySQL server")

    with connection.cursor() as cursor:
        select_query = "SELECT * FROM Einkommensdaten"

        cursor.execute(select_query)
        rows = cursor.fetchall()

        for row in rows:
            print(row)

except Error as e:
    print("Error connecting to MySQL:", e)

finally:
    if 'connection' in locals() and connection.is_connected():
        # Close connection
        connection.close()
        print("MySQL connection closed")